name: CI/CD Pipeline with Custom Scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Make scripts executable
    - name: Make scripts executable
      run: chmod +x scripts/*.sh
      
    # Run your installation script with empty input
    - name: Run installation script
      run: ./scripts/install.sh < /dev/null
      shell: bash
      
    # Run tests script
    - name: Run tests
      run: ./scripts/run_tests.sh
      shell: bash
      
    # Optionally, run backend
    # - name: Verify backend startup
      # run: ./scripts/run_backend.sh
      # shell: bash
      # continue-on-error: true
      # timeout-minutes: 5
      
    # Optionally, run frontend
    # - name: Verify frontend startup
      # run: ./scripts/run_frontend.sh
      # shell: bash
      # continue-on-error: true
      # timeout-minutes: 5
